os: linux
arch: amd64
dist: bionic
language: go
go:
  - 1.13

before_install:
  - go get -v github.com/mitchellh/gox@v1.0.1

install:
  - go get -v ./...

before_script:
  - true

script:
  - gox -osarch="linux/386 linux/amd64 linux/arm linux/arm64 darwin/amd64 darwin/386 windows/amd64 windows/386"
    -output="out/{{.Dir}}-{{.OS}}-{{.Arch}}" -ldflags "-s -w -X jdel.org/gosspks/cfg.Version=${TRAVIS_BRANCH}"

after_script:
  - true

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file:
    - out/gosspks-darwin-386
    - out/gosspks-darwin-amd64
    - out/gosspks-linux-386
    - out/gosspks-linux-amd64
    - out/gosspks-linux-arm
    - out/gosspks-windows-386.exe
    - out/gosspks-windows-amd64.exe
  draft: true
  skip_cleanup: true
  on:
    tags: true
