os: linux
arch: amd64
dist: bionic
language: go
go:
  - 1.14.x

before_install:
  - go get -v github.com/mitchellh/gox@v1.0.1

install:
  - go get -v ./...

before_script:
  - true

script:
  - gox -osarch="linux/amd64 linux/arm linux/arm64 windows/amd64"
    -output="out/{{.Dir}}-{{.OS}}-{{.Arch}}" -ldflags "-s -w -X jdel.org/gosspks/cfg.Version=${TRAVIS_BRANCH}"

after_script:
  - true

before_deploy:
  - true

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: out/*
  draft: true
  skip_cleanup: true
  on:
    tags: true
